
  # After registering a name on build.snapcraft.io, commit an uncommented line:
  name: guiscrcpy
  version: '1.11.0' # just for humans, typically '1.2+git' or '1.3.2'
  summary: An opensource GUI for android screen mirroring# 79 char long summary
  description: |
    A full fledged GUI integration for the award winning open source scrcpy, for 
    Android Screen mirroring
  
  grade: stable # must be 'stable' to release into candidate/stable channels
  confinement: devmode #use 'strict' once you have the right plugs and slots
  # plugs: ['desktop','framebuffer', 'home', 'opengl', 'x11', 'desktop-legacy']
 
  architectures:
        - build-on: amd64
          
  parts:
    pre-guiscrcpy:
     
      after: [desktop-qt5]
      # See 'snapcraft plugins'
      plugin: dump
      source: https://github.com/srevinsaju/guiscrcpy/archive/master.zip
      #requirements: requirements.txt
      build-packages: [python3-pip]
         
    guiscrcpy:
      after: [pre-guiscrcpy]
      plugin: dump
      source: https://github.com/srevinsaju/guiscrcpy/archive/master.zip
      build-packages: [python3-pip]

      override-prime: |
              echo "Installing PIP modules"
              snapcraftctl build
              python3 -m pip install PyQt5 psutil qdarkstyle PyInstaller
              echo "Copying files"
              cp -r  ../parts/guiscrcpy/src/guiscrcpy-master .
              echo "Generating Binary"
              python3 -m PyInstaller -n guiscrcpy -y guiscrcpy-master/guiscrcpy/__main__.py
              echo * 
              echo "Compiled Successfully"

      stage-packages: [adb]        
      

  apps:
   guiscrcpy:
   

     command: desktop-launch $SNAP/dist/guiscrcpy
     plugs: ['desktop','content','dbus','framebuffer', 'home', 'opengl', 'x11', 'desktop-legacy','network','network-bind','unity7']
     
    
