
  # After registering a name on build.snapcraft.io, commit an uncommented line:
  name: guiscrcpy
  version: '1.11.0' # just for humans, typically '1.2+git' or '1.3.2'
  summary: An opensource GUI for android screen mirroring# 79 char long summary
  description: |
    A full fledged GUI integration for the award winning open source scrcpy, for 
    Android Screen mirroring
  
  grade: stable # must be 'stable' to release into candidate/stable channels
  confinement: strict # use 'strict' once you have the right plugs and slots
  # plugs: ['desktop','framebuffer', 'home', 'opengl', 'x11', 'desktop-legacy']
  # nbase: core18
  parts:
    guiscrcpy:
      
      after: [desktop-qt5]
      # See 'snapcraft plugins'
      plugin: python
      python-version: python3
      source: https://github.com/srevinsaju/guiscrcpy/archive/master.zip
      #requirements: requirements.txt
      # fgfstage-packages: [python3-pip]
      python-packages: [PyQt5, psutil,qdarkstyle]
      
      

  apps:
   guiscrcpy:
   

     command: desktop-launch python3 $SNAP/guiscrcpy-master/guiscrcpy
     plugs: ['desktop','framebuffer', 'home', 'opengl', 'x11', 'desktop-legacy']
     
    
