
  # After registering a name on build.snapcraft.io, commit an uncommented line:
  name: guiscrcpy
  version: '1.11.0' # just for humans, typically '1.2+git' or '1.3.2'
  summary: An opensource GUI for android screen mirroring# 79 char long summary
  description: |
    A full fledged GUI integration for the award winning open source scrcpy, for 
    Android Screen mirroring
  
  grade: stable # must be 'stable' to release into candidate/stable channels
  confinement: classic # use 'strict' once you have the right plugs and slots
  base: core18
  parts:
    guiscrcpy:
      
      
      # See 'snapcraft plugins'
      plugin: dump
      source: https://github.com/srevinsaju/guiscrcpy/archive/master.zip
      # python-version: python3
      
      # python-packages: [PyQt5, psutil,qdarkstyle]
      build-packages: 
        - python3.6
        - python3.6-pip
        - python3.6-venv
      override-prime: |
          snapcraftctl build
          cp -r  ../parts/guiscrcpy/src/guiscrcpy-master .
          python3.6 -m venv venv
          ./venv/bin/pip3.6 install PyQt5 psutil qdarkstyle PyInstaller
          #./venv/bin/python3 -m PyInstaller -n guiscrcpy guiscrcpy-master/guiscrcpy/__main__.py --noconfirm --clea --distpath guiscrcpy-master/guiscrcpy/dist
          chmod a+rwx *
          #chmod a+rwx guiscrcpy-master/guiscrcpy/dist/*
          #cp -r guiscrcpy-master/guiscrcpy/dist  ./../../../prime/
          #prime: [+venv/*] 

  apps:
   guiscrcpy:
           #build-packages: 
           #- python3-pip
     command: bash -c '$SNAP/venv/bin/pip3.6 install PyQt5 psutil qdarkstyle; $SNAP/venv/bin/python3.6 $SNAP/guiscrcpy-master/guiscrcpy'
     
     
  
