
name: Continuous
on: 
  - push

jobs:
  Wheel:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        version: ['3.8']
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.version }}

    - name: Build wheel
      run: |
        python -m pip install wheel
        python setup.py bdist_wheel
        export VERSION=$(ls dist)
        
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: guiscrcpy-continuous-none-any-py3.whl
        path: dist/${{ env.VERSION }}

  AppImage:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        version: ['3.8']

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.version }}
    - name: Download dependencies
      run: |
        sudo apt install libxkbcommon0 libxcb-xkb-dev libxkbcommon-x11-0 libxcb-xkb1
    - name: Test AppImage
      run: |
        python -m pip install python-appimage
        echo $(realpath .) > appimage/requirements.txt
        python -m python_appimage build app appimage \
                                            --linux-tag=manylinux1_x86_64
    
    - name: Extract AppImage
      run: |
        ./guiscrcpy-x86_64.AppImage --appimage-extract
        
    - name: Patch PyQt5
      run: |
        cp -L /usr/lib/x86_64-linux-gnu/libxkbcommon* squashfs-root/usr/lib/.
        cp -L /usr/lib/x86_64-linux-gnu/libxcb-xkb.so.1 squashfs-root/usr/lib/.
    
    - name: Download scrcpy
      run: |
        wget -c https://github.com/$(wget -q https://github.com/srevinsaju/scrcpy-appimage/releases -O - | grep "scrcpy*.AppImage" | head -n 1 | cut -d '"' -f 2)
        chmod +x scrcpy*.AppImage
        ./scrcpy*.AppImage --appimage-extract

    - name: Download AppImage Tool
      run: |
        wget https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage
        chmod +x ./appimagetool-x86_64.AppImage
 
    - name: Reimage AppImage
      run: |
        rm ./guiscrcpy-x86_64.AppImage
        ./appimagetool-x86_64.AppImage squashfs-root -n -u 'gh-releases-zsync|srevinsaju|guiscrcpy|latest|guiscrcpy*.AppImage.zsync'
        mkdir -p appimage_dist
        mv guiscrcpy*.AppImage* appimage_dist/.
 
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: guiscrcpy-continuous-x86_64.AppImage
        path: 'appimage_dist/'



  Windows:
    name: Windows
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip3 install PyInstaller
          pip3 install -r requirements.txt
          pip3 install . 
          echo Done
          
      - name: Create .exe
        run: |
          python -m PyInstaller guiscrcpy-windows.spec
      - name: Upload artifact
        uses: actions/upload-artifact@v1.0.0
        with:
          # Artifact name
          name: guiscrcpy-continuous.exe
          # Directory containing files to upload
          path: dist/guiscrcpy.exe


  Windows-PySide2:
    name: Windows-PySide2
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        
      - name: Install dependencies
        run: |
          sed -i 's,PyQt5,PySide2,g' requirements.txt
          sed -i 's,PyQt5,PySide2,g' setup.py
          python -m pip install --upgrade pip
          pip3 install PyInstaller
          pip3 install -r requirements.txt
          pip3 install . 
          echo Done
          
      - name: Create .exe
        run: |
          python -m PyInstaller guiscrcpy-windows.spec
          mv dist/guiscrcpy.exe dist/guiscrcpy-pyside2.exe
      - name: Upload artifact
        uses: actions/upload-artifact@v1.0.0
        with:
          # Artifact name
          name: guiscrcpy-pyside2-continuous.exe
          # Directory containing files to upload
          path: dist/guiscrcpy-pyside2.exe


  Release:
    needs: [Windows, AppImage, Wheel, Windows-PySide2]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [3.8]

    steps:
    - uses: actions/download-artifact@v1
      with:
        name: guiscrcpy-continuous.exe
    - uses: actions/download-artifact@v1
      with:
        name: guiscrcpy-pyside2-continuous.exe
    - uses: actions/download-artifact@v1
      with:
        name: guiscrcpy-continuous-none-any-py3.whl
    - uses: actions/download-artifact@v1
      with:
        name: guiscrcpy-continuous-x86_64.AppImage

    - name: Release
      uses: marvinpinto/action-automatic-releases@latest
      if: github.ref == 'refs/heads/master' && startsWith(github.ref, 'refs/tags/') != true
      with:
        automatic_release_tag: continuous
        title: continuous
        files: |
          guiscrcpy-continuous.exe
          guiscrcpy-pyside2-continuous.exe
          guiscrcpy-PySide2-continuous-x86_64.AppImage
          guiscrcpy-continuous-x86_64.AppImage
          guiscrcpy-continuous-none-any-py3.whl
          
        repo_token: ${{ secrets.GITHUB_TOKEN }}
